### ISSUE TITLE
Stops working in newest version 1.0.0.7

### ISSUE THREAD

**Issue by Battler624** [madk/LoLAccountChecker#10]
Just tried using the latest version (was using a version from feb 5. didn't know the number) and this new version stops working after a little while (doesn't take long really).

I stopped using last version because since the update it gives me a version error on euw.

The new version is awesome but two things i wish to be done immediate write to file every success and show us a window (like showing us CMD in the older version) to see the what is going on from success to errors.

**Comment by Battler624** [comment]
the older version error says *wrong client version for server*

**Comment by Battler624** [comment]
So far the new version doesn't write to file and stopped 3 times in normal user mode : 
1 right after clicking check then right near the end then in the middle so its random

and twice in admin, completely random. one after maybe 8 seconds the other maybe 20.

**Comment by hatecoore** [comment]
for me allway around the last 10 accs

**Comment by hatecoore** [comment]
only finished one the other all stopped near the last acc

**Comment by hatecoore** [comment]
with one thread it works everytime but slow -_-

**Comment by Battler624** [comment]
Tried compiling myself, had to delete debug error because it was giving me a ";" exception line 84 i think.

But still even compiling myself it didn't save.

**Comment by madk** [comment]
Should be fixed, try the new version

**Comment by Battler624** [comment]
Fixed mostly, now only if i have export errors on it wont save (gets stuck at last one) but no crashes, Thanks!
