### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by fyermen8** [madk/LoLAccountChecker#14]
With the newest update (2.0.0.0) it just crashes.

![image](https://cloud.githubusercontent.com/assets/9354968/6205590/d3e7fe54-b573-11e4-87d8-c049e36d0407.png)
(Not responding in Dutch)

Probably because it wants to add all the data at once, and it just crashes.

**Comment by Shichifukujin** [comment]
Same issue. It works fine with a single account, try loading a list of any decent size and it just crashes

**Comment by patkazop** [comment]
same

**Comment by 50ouncebrew** [comment]
New update still crashing..

**Comment by Shichifukujin** [comment]
New update, still crashing.  

Tried it with 1 account, worked fine. Then 25 and it crashed. Same issue with 10 accounts.  I then tried 14 accounts I know are valid and correct and it still crashed.

OS: Windows 8.1

**Comment by 50ouncebrew** [comment]
yeah same win 8.1 1 worked then crash

**Comment by madk** [comment]
http://puu.sh/g3tMX/4d4401f998.zip

Use this one and send me the files that will be created on the Logs folder.

**Comment by Shichifukujin** [comment]
I used that one and there are no files created in the log folder

**Comment by madk** [comment]
Did it create the folder?

**Comment by Shichifukujin** [comment]
It created a folder but the folder had no items in it.

**Comment by madk** [comment]
http://puu.sh/g3DVP/37e03bf3b6.zip

This one should write the files now.

**Comment by Shichifukujin** [comment]
The most recent on you linked does not create a folder or logs. >.<  Tried it multiple times.

**Comment by Hantan1080** [comment]
Yeah I'm also still have the crash issues @madk 

Love the new design though

**Comment by BigBudda87** [comment]
on win 7 x64 and win 8.1 x64 i get unable to authenticate someone has an idea how to fix this?

**Comment by Maelzel** [comment]
Same here, just crash sometimes and doesn't authenticate and i can login with that account

**Comment by superei** [comment]
It crash then he check a Lvl 1 acc newest version 2.0.0.3

**Comment by Zettiee** [comment]
Still crash :(

**Comment by 50ouncebrew** [comment]
madk yu still with us? :o D:

**Comment by Shichifukujin** [comment]
Tried the newest one you just released and the crashing issue still persist for me. Thank you so much for working on this though :) By far the best checker out there

**Comment by 50ouncebrew** [comment]
ty working !!!

**Comment by madk** [comment]
PVPNetConnect is the cause of the crash, not the Checker.

**Comment by iveg** [comment]
before riots released 5.4 patch. i used v. 1.0.0.8 of ur checker and it was worked perfectly without any crashes compare to v. 2.0.0.2(crashes every time).
and now after riots patched LOL any versions of ur great soft didn't work 
1.0.0.8 - because of patch
and all new versions with grafical feature - because of crash bug
but thx for ur work :)

**Comment by madk** [comment]
https://github.com/madk/LoLAccountChecker/tree/5d36573b0f2599772c4d0c5a45bd70368391d578

This is the old code, if you want to use it you just need to change the client version to the new one.

https://github.com/madk/LoLAccountChecker/blob/5d36573b0f2599772c4d0c5a45bd70368391d578/Client.cs#L33

**Comment by LitePenguins** [comment]
How can you recompile everything to a .exe file once you change the client version? Sorry, I am new to C# and have no idea what I'm doing in Visual Studio ._.

**Comment by subzrk** [comment]
Same error with the latest version, hope you can find a fix, thnx anyway ^^

**Comment by Kek420** [comment]
The program still crashes for me after checking about 10/20 accounts. If there is a solution for this please enlighten us, thanks.

**Comment by 50ouncebrew** [comment]
Thank you!! checked 80 accs no crash <3 keep it up
