### ISSUE TITLE
Pbe And NA Crashing

### ISSUE THREAD

**Issue by 50ouncebrew** [madk/LoLAccountChecker#15]
Hey pbe crashes when i load in 3 accounts also madk what forums are you from like do you post on leakforums hackforum? or just here 

Also NA is crashing to when i load 100 accs even with 20 accs

**Comment by madk** [comment]
I posted on http://nulled.io/

**Comment by patkazop** [comment]
yea its the same for me crash. but the first time i use it it always work. the second time nothing ;/
