### ISSUE TITLE
New update still dont work crashing

### ISSUE THREAD

**Issue by 50ouncebrew** [madk/LoLAccountChecker#17]
Its still crashing . :{{

**Comment by RoLiX986** [comment]
crashing too on 2 computers 
1- win 7(with all versions of framework)
2- win 8(installed framework ver.1.4.1)
tried to check ru/euw server
crashing after second founded account
p.s sorry for my english :)

**Comment by Perplexity** [comment]
I know why it's crashing. It creates a new thread per account, and eventually it just uses up all of your memory. I've made my own checker that works fine, you just have to set the limits :)

**Comment by bamasmith** [comment]
Well mind posting a link?
