### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by horato** [madk/LoLAccountChecker#26]
Client.cs line ~147 loginPacket.EmailStatus == null => replace causes null pointer exception.
Wrapping the 2 lines into an if (loginPacket.EmailStatus != null) works.

**Comment by madk** [comment]
Are you using the PVPNetConnect Lib that i forked?

**Comment by horato** [comment]
I am using libs from 2.0.0.3 release and latest source code (with changes up to and including Feb 26, 2015)

**Comment by d3ullist** [comment]
This issue can be fixed by change a small line of code in the Client.cs (line 147)
var emailStatus = "";

            if (loginPacket.EmailStatus != null)
            {
                emailStatus = loginPacket.EmailStatus.Replace('_', ' ');
                Data.EmailStatus = Char.ToUpper(emailStatus[0]) + emailStatus.Substring(1);
            }
            else
                 emailStatus = loginPacket.EmailStatus;
It won't crash anymore, but can return some accounts as empty

**Comment by madk** [comment]
I just pushed a fix. 
If you guys wanna suggest any change on the code, do it on a [Pull Request](https://help.github.com/articles/creating-a-pull-request/)

**Comment by 50ouncebrew** [comment]
hey madk so your not gonna release a update version just source code?

**Comment by farissi** [comment]
Can you please push a release? or can someone PM me the compiled version, thanks in advance !

**Comment by horato** [comment]
@d3ullist the else part is not really necessary since you don't use var emailStatus anywhere else.

**Comment by d3ullist** [comment]
@horato the else part is in fact necessary, but I guess "Unknown" as it has been placed in the code fix is more fitting. EmailStatus is the status whether a email is validated or not. Returning blank is kind of user unfriendly.

**Comment by horato** [comment]
@d3ullist I was just refering to your solution, in that case the else part does nothing. What madk pushed seems like the best solution.
