### ISSUE TITLE
Why cant it export the Accounts to a .txt file like it did before?

### ISSUE THREAD

**Issue by mangosd1337** [madk/LoLAccountChecker#32]
So, why is the accountdata now showing in the .txt file anymore? :/
I wont have to scan every single textfile over and over again just to find one account :o 
could you pls make it so that this is possible? would be cool :D

**Comment by madk** [comment]
If you wanna import checked accounts you need a json file that you exported by clicking on the export button on the main window. The file that you showed me on nulled.io is a text-file from an old version (2.0.0.3 or less).
