### ISSUE TITLE
[Bug] ShowMessageAsync Error

### ISSUE THREAD

**Issue by unSatisfied9** [madk/LoLAccountChecker#38]
Whenever the accounts are finished being checked, a message should popup on the MainWindow saying that "All the accounts have been checked!" with the following line of code in Checker.cs:

await MainWindow.Instance.ShowMessageAsync("Done", "All the accounts have been checked!");

I get the following error: The calling thread cannot access this object because a different thread owns it.
Although this line of code doesn't work, all other calls to Main.Instance (in Checker.cs) work properly (Example:  MainWindow.Instance.UpdateControls()). I think it has something to do with the call being Async.

**Comment by madk** [comment]
Fixed fe579282a7972337c9ff1fe42947869d3c9cd84d
