### ISSUE TITLE
Wrong client version for server

### ISSUE THREAD

**Issue by MrJaf** [madk/LoLAccountChecker#45]
Hi, after START checking the worked acc's this error only show up " Wrong client version for server "
 please fix this problem...

**Comment by Satnamigyz** [comment]
Open file settings.json with notepad or any other text editor software.
Replace ClientVersion line with this one.
When application requests to update (each start of program) just click cancel.

  "ClientVersion": "5.8.15_04_30_12_11"

**Comment by MrJaf** [comment]
thanks <3 <3 <3

**Comment by Backdoorz** [comment]
Hello even if i change client version like this. It still shows "Wrong client version for server"

**Comment by madk** [comment]
fixed

**Comment by winttw** [comment]
Same problem "Wrong client version for server"
