### ISSUE TITLE
Unregisted error

### ISSUE THREAD

**Issue by JouzaLoL** [madk/LoLAccountChecker#5]
It is working fine, but on a lot of accounts it is giving me this:

![](http://i.gyazo.com/836ecd0aa4b4f0fcdb383d7e1d0cddee.png)
I don't know what that is and how to fix it :/

**Comment by madk** [comment]
There are something with those accounts that doesnt let you loggin in. Probably they require you to change the password in order to login. Check in the LoL's Client
