### ISSUE TITLE
Can't Import From Text

### ISSUE THREAD

**Issue by BiscuitEdi** [madk/LoLAccountChecker#50]
Here's a gif showing the problem.
It worked when I used it the last time (about a week ago).
I think the update to ImportWindow.xaml.cs might have caused it.

**Comment by madk** [comment]
What's the issue? Does it make it stop working? If so, send me the log file.

**Comment by BiscuitEdi** [comment]
I'm sorry I uploaded the gif but forgot to link it here.
http://i.imgur.com/Kqm3LT5.gifv
Here's the log file: http://drp.io/f/mJ7nPfekl

**Comment by madk** [comment]
The file you are trying to import doesn't have the format '''username:password'''

**Comment by BiscuitEdi** [comment]
Oh I didn't even notice that.
Thanks for the help and sorry for inconveniencing you.
